services:
  - type: web
    # Cambiar por un nombre único antes de crear el Blueprint.
    name: webdev-laravel-starter
    runtime: docker
    plan: free
    region: virginia
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    autoDeployTrigger: checksPass

    envVars:
      - key: APP_NAME
        value: Desarrollo Web con Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: es_ES
      - key: APP_TIMEZONE
        value: America/Costa_Rica

      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require

      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"

      - key: CACHE_STORE
        value: database

      - key: QUEUE_CONNECTION
        value: sync

      - key: MAIL_MAILER
        value: log